Add some missing types
onmotion/react-native-autocomplete-dropdown pull request #28
Opened 2022-03-23 16:48 UTC by drastus

Fixes #27

2022-03-23 16:55 UTC, onmotion requested changes

2022-03-23 16:55 UTC, onmotion commented on src/index.d.ts
> +  renderItem?: (item: TAutocompleteDropdownItem, searchText: string) => JSX.Element | undefined
why not just return empty jsx`<></>`?

2022-03-23 16:55 UTC, onmotion commented on src/index.d.ts
> +  ItemSeparatorComponent?: JSX.Element | false
why do you need false? I think `ItemSeparatorComponent?: JSX.Element` would be enough

2022-03-24 07:28 UTC, drastus commented on src/index.d.ts
> +  renderItem?: (item: TAutocompleteDropdownItem, searchText: string) => JSX.Element | undefined
Indeed, it works. Removed `undefined`.

2022-03-24 07:29 UTC, drastus commented on src/index.d.ts
> +  ItemSeparatorComponent?: JSX.Element | false
You're right, removed `false`.

2022-03-24 07:36 UTC, merged